ALTER TABLE public.periodo
    ADD COLUMN IF NOT EXISTS descricao VARCHAR(20);

UPDATE public.periodo
SET descricao = CASE mes
    WHEN 1 THEN 'JANEIRO'
    WHEN 2 THEN 'FEVEREIRO'
    WHEN 3 THEN 'MARCO'
    WHEN 4 THEN 'ABRIL'
    WHEN 5 THEN 'MAIO'
    WHEN 6 THEN 'JUNHO'
    WHEN 7 THEN 'JULHO'
    WHEN 8 THEN 'AGOSTO'
    WHEN 9 THEN 'SETEMBRO'
    WHEN 10 THEN 'OUTUBRO'
    WHEN 11 THEN 'NOVEMBRO'
    WHEN 12 THEN 'DEZEMBRO'
    ELSE 'INVALIDO'
END
WHERE descricao IS NULL;

ALTER TABLE public.periodo
    ALTER COLUMN descricao SET NOT NULL;
